import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const dbPath = join(__dirname, '../../banco_palavras.db');

export const initialWords = [
  ['morango', 'fruta'],
  ['banana', 'fruta'],
  ['cachorro', 'animal'],
  ['gato', 'animal'],
  ['computador', 'tecnologia'],
  ['smartphone', 'tecnologia'],
  ['cadeira', 'objeto'],
  ['mesa', 'objeto'],
  ['quadrado', 'formato'],
  ['círculo', 'formato'],
  ['alegria', 'sentimento'],
  ['tristeza', 'sentimento'],
  ['paris', 'cidade'],
  ['roma', 'cidade'],
  ['pêra', 'fruta'],
  ['kiwi', 'fruta'],
  ['manga', 'fruta'],
  ['abacate', 'fruta'],
  ['ameixa', 'fruta'],
  ['framboesa', 'fruta'],
  ['mirtilo', 'fruta'],
  ['coco', 'fruta'],
  ['figo', 'fruta'],
  ['carambola', 'fruta'],
  ['maracujá', 'fruta'],
  ['jaca', 'fruta'],
  ['cervo', 'animal'],
  ['panda', 'animal'],
  ['canguru', 'animal'],
  ['golfinho', 'animal'],
  ['ornitorrinco', 'animal'],
  ['camaleão', 'animal'],
  ['hipopótamo', 'animal'],
  ['esquilo', 'animal'],
  ['gavião', 'animal'],
  ['ouriço', 'animal'],
  ['papagaio', 'animal'],
  ['jacaré', 'animal'],
  ['falcão', 'animal'],
  ['chinchila', 'animal'],
  ['antílope', 'animal'],
  ['lontra', 'animal'],
  ['caracol', 'animal'],
  ['bicho-preguiça', 'animal'],
  ['camundongo', 'animal'],
  ['lagosta', 'animal'],
  ['peixe-boi', 'animal'],
  ['arraia', 'animal'],
  ['lêmure', 'animal'],
  ['vaca', 'animal'],
  ['galo', 'animal'],
  ['peru', 'animal'],
  ['alpaca', 'animal'],
  ['lhama', 'animal'],
  ['camarão', 'animal'],
  ['tamanduá', 'animal'],
  ['gambá', 'animal'],
  ['pavão', 'animal'],
  ['raposa', 'animal'],
  ['texugo', 'animal'],
  ['tritão', 'animal'],
  ['salamandra', 'animal'],
  ['dragão-barbudo', 'animal'],
  ['computador de bordo', 'tecnologia'],
  ['smartwatch', 'tecnologia'],
  ['fones de ouvido', 'tecnologia'],
  ['microfone', 'tecnologia'],
  ['caixa de som', 'tecnologia'],
  ['webcam', 'tecnologia'],
  ['gps', 'tecnologia'],
  ['scanner', 'tecnologia'],
  ['notebook', 'tecnologia'],
  ['console', 'tecnologia'],
  ['controle remoto', 'tecnologia'],
  ['modem', 'tecnologia'],
  ['roteador', 'tecnologia'],
  ['cadeado', 'objeto'],
  ['abajur', 'objeto'],
  ['ventilador', 'objeto'],
  ['travesseiro', 'objeto'],
  ['cortina', 'objeto'],
  ['pente', 'objeto'],
  ['escova de cabelo', 'objeto'],
  ['varal', 'objeto'],
  ['pregador', 'objeto'],
  ['tampa', 'objeto'],
  ['chaleira', 'objeto'],
  ['bule', 'objeto'],
  ['frigideira', 'objeto'],
  ['talher', 'objeto'],
  ['chave', 'objeto'],
  ['controle de videogame', 'objeto'],
  ['rádio', 'objeto'],
  ['carteira', 'objeto'],
  ['cofre', 'objeto'],
  ['trapezoide', 'formato'],
  ['losango', 'formato'],
  ['paralelogramo', 'formato'],
  ['heptágono', 'formato'],
  ['decágono', 'formato'],
  ['dodecágono', 'formato'],
  ['oval', 'formato'],
  ['coração', 'formato'],
  ['nuvem', 'formato'],
  ['espiral', 'formato'],
  ['borboleta', 'formato'],
  ['estrela do mar', 'formato'],
  ['constelação', 'formato'],
  ['saudade', 'sentimento'],
  ['nostalgia', 'sentimento'],
  ['remorso', 'sentimento'],
  ['desespero', 'sentimento'],
  ['ânsia', 'sentimento'],
  ['euforia', 'sentimento'],
  ['compaixão', 'sentimento'],
  ['melancolia', 'sentimento'],
  ['orgulho', 'sentimento'],
  ['admiração', 'sentimento'],
  ['conforto', 'sentimento'],
  ['alívio', 'sentimento'],
  ['tédio', 'sentimento'],
  ['paz', 'sentimento'],
  ['curiosidade', 'sentimento'],
  ['determinação', 'sentimento'],
  ['equador', 'cidade'],
  ['barcelona', 'cidade'],
  ['miami', 'cidade'],
  ['houston', 'cidade'],
  ['las vegas', 'cidade'],
  ['toronto', 'cidade'],
  ['ottawa', 'cidade'],
  ['calgary', 'cidade'],
  ['auckland', 'cidade'],
  ['wellington', 'cidade'],
  ['bogotá', 'cidade'],
  ['quito', 'cidade'],
  ['caracas', 'cidade'],
  ['santo domingo', 'cidade'],
  ['porto príncipe', 'cidade'],
  ['manágua', 'cidade'],
  ['belmopan', 'cidade'],
  ['la paz', 'cidade'],
  ['assunção', 'cidade'],
  ['montevidéu', 'cidade'],
  ['kuala lumpur', 'cidade'],
  ['taipei', 'cidade'],
  ['pyongyang', 'cidade'],
  ['cabul', 'cidade'],
  ['teerã', 'cidade'],
  ['bagdá', 'cidade'],
  ['damasco', 'cidade'],
  ['beirute', 'cidade'],
  ['jerusalém', 'cidade'],
  ['riyadh', 'cidade'],
  ['doha', 'cidade'],
  ['muscat', 'cidade'],
  ['astana', 'cidade'],
  ['tashkent', 'cidade'],
  ['ulaanbaatar', 'cidade'],
  ['addis abeba', 'cidade'],
  ['cartum', 'cidade'],
  ['abidjan', 'cidade'],
  ['kigali', 'cidade'],
  ['luanda', 'cidade'],
  ['maputo', 'cidade'],
  ['harare', 'cidade'],
  ['porto', 'cidade'],
  ['sevilha', 'cidade'],
  ['bilbao', 'cidade'],
  ['florença', 'cidade'],
  ['san marino', 'cidade'],
  ['ljubljana', 'cidade'],
  ['vilnius', 'cidade'],
  ['riga', 'cidade'],
  ['tallinn', 'cidade'],
  ['alface', 'verdura'],
  ['acelga', 'verdura'],
  ['agrião', 'verdura'],
  ['couve', 'verdura'],
  ['repolho', 'verdura'],
  ['brócolis', 'verdura'],
  ['almeirão', 'verdura'],
  ['espinafre', 'verdura'],
  ['rúcula', 'verdura'],
  ['chicória', 'verdura'],
  ['mostarda', 'verdura'],
  ['escarola', 'verdura'],
];
