name: Deploy Backend to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        project_id: "backend-454404"
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --project "backend-454404"
